/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayPulseRouteImport } from './routes/play-pulse'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminChildrenRouteImport } from './routes/admin.children'
import { Route as AdminEducatorsRouteImport } from './routes/admin.educators'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminOrgsRouteImport } from './routes/admin.orgs'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminProgressRouteImport } from './routes/admin.progress'
import { Route as AdminTtpRouteImport } from './routes/admin.ttp'
import { Route as AuthMicrosoftCallbackRouteImport } from './routes/auth.microsoft-callback'
import { Route as OrgIndexRouteImport } from './routes/org.index'
import { Route as OrgEnrollRouteImport } from './routes/org.enroll'
import { Route as OrgSupportersRouteImport } from './routes/org.supporters'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as PoliciesPrivacyPolicyRouteImport } from './routes/policies.privacy-policy'
import { Route as PoliciesTermsOfServiceRouteImport } from './routes/policies.terms-of-service'
import { Route as PlansPlanIdIndexRouteImport } from './routes/plans.$planId.index'
import { Route as PlansPlanIdEntryIdRouteImport } from './routes/plans.$planId.$entryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPulseRoute = PlayPulseRouteImport.update({
  id: '/play-pulse',
  path: '/play-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChildrenRoute = AdminChildrenRouteImport.update({
  id: '/admin/children',
  path: '/admin/children',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEducatorsRoute = AdminEducatorsRouteImport.update({
  id: '/admin/educators',
  path: '/admin/educators',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrgsRoute = AdminOrgsRouteImport.update({
  id: '/admin/orgs',
  path: '/admin/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgressRoute = AdminProgressRouteImport.update({
  id: '/admin/progress',
  path: '/admin/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTtpRoute = AdminTtpRouteImport.update({
  id: '/admin/ttp',
  path: '/admin/ttp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMicrosoftCallbackRoute = AuthMicrosoftCallbackRouteImport.update({
  id: '/auth/microsoft-callback',
  path: '/auth/microsoft-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgEnrollRoute = OrgEnrollRouteImport.update({
  id: '/org/enroll',
  path: '/org/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSupportersRoute = OrgSupportersRouteImport.update({
  id: '/org/supporters',
  path: '/org/supporters',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyPolicyRoute = PoliciesPrivacyPolicyRouteImport.update({
  id: '/policies/privacy-policy',
  path: '/policies/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesTermsOfServiceRoute = PoliciesTermsOfServiceRouteImport.update({
  id: '/policies/terms-of-service',
  path: '/policies/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdIndexRoute = PlansPlanIdIndexRouteImport.update({
  id: '/plans/$planId/',
  path: '/plans/$planId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdEntryIdRoute = PlansPlanIdEntryIdRouteImport.update({
  id: '/plans/$planId/$entryId',
  path: '/plans/$planId/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/account': typeof AccountRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/play-pulse': typeof PlayPulseRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/educators': typeof AdminEducatorsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/ttp': typeof AdminTtpRoute
  '/auth/microsoft-callback': typeof AuthMicrosoftCallbackRoute
  '/org/enroll': typeof OrgEnrollRoute
  '/org/supporters': typeof OrgSupportersRoute
  '/policies/privacy-policy': typeof PoliciesPrivacyPolicyRoute
  '/policies/terms-of-service': typeof PoliciesTermsOfServiceRoute
  '/admin/': typeof AdminIndexRoute
  '/org/': typeof OrgIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/plans/$planId/$entryId': typeof PlansPlanIdEntryIdRoute
  '/plans/$planId/': typeof PlansPlanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/account': typeof AccountRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/play-pulse': typeof PlayPulseRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/educators': typeof AdminEducatorsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/ttp': typeof AdminTtpRoute
  '/auth/microsoft-callback': typeof AuthMicrosoftCallbackRoute
  '/org/enroll': typeof OrgEnrollRoute
  '/org/supporters': typeof OrgSupportersRoute
  '/policies/privacy-policy': typeof PoliciesPrivacyPolicyRoute
  '/policies/terms-of-service': typeof PoliciesTermsOfServiceRoute
  '/admin': typeof AdminIndexRoute
  '/org': typeof OrgIndexRoute
  '/plans': typeof PlansIndexRoute
  '/plans/$planId/$entryId': typeof PlansPlanIdEntryIdRoute
  '/plans/$planId': typeof PlansPlanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/account': typeof AccountRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/play-pulse': typeof PlayPulseRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/educators': typeof AdminEducatorsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/ttp': typeof AdminTtpRoute
  '/auth/microsoft-callback': typeof AuthMicrosoftCallbackRoute
  '/org/enroll': typeof OrgEnrollRoute
  '/org/supporters': typeof OrgSupportersRoute
  '/policies/privacy-policy': typeof PoliciesPrivacyPolicyRoute
  '/policies/terms-of-service': typeof PoliciesTermsOfServiceRoute
  '/admin/': typeof AdminIndexRoute
  '/org/': typeof OrgIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/plans/$planId/$entryId': typeof PlansPlanIdEntryIdRoute
  '/plans/$planId/': typeof PlansPlanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/account'
    | '/check-in'
    | '/dashboard'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/play-pulse'
    | '/progress'
    | '/reset-password'
    | '/signup'
    | '/subscription'
    | '/admin/audit'
    | '/admin/children'
    | '/admin/educators'
    | '/admin/homepage'
    | '/admin/orgs'
    | '/admin/plans'
    | '/admin/progress'
    | '/admin/ttp'
    | '/auth/microsoft-callback'
    | '/org/enroll'
    | '/org/supporters'
    | '/policies/privacy-policy'
    | '/policies/terms-of-service'
    | '/admin/'
    | '/org/'
    | '/plans/'
    | '/plans/$planId/$entryId'
    | '/plans/$planId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/account'
    | '/check-in'
    | '/dashboard'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/play-pulse'
    | '/progress'
    | '/reset-password'
    | '/signup'
    | '/subscription'
    | '/admin/audit'
    | '/admin/children'
    | '/admin/educators'
    | '/admin/homepage'
    | '/admin/orgs'
    | '/admin/plans'
    | '/admin/progress'
    | '/admin/ttp'
    | '/auth/microsoft-callback'
    | '/org/enroll'
    | '/org/supporters'
    | '/policies/privacy-policy'
    | '/policies/terms-of-service'
    | '/admin'
    | '/org'
    | '/plans'
    | '/plans/$planId/$entryId'
    | '/plans/$planId'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/account'
    | '/check-in'
    | '/dashboard'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/play-pulse'
    | '/progress'
    | '/reset-password'
    | '/signup'
    | '/subscription'
    | '/admin/audit'
    | '/admin/children'
    | '/admin/educators'
    | '/admin/homepage'
    | '/admin/orgs'
    | '/admin/plans'
    | '/admin/progress'
    | '/admin/ttp'
    | '/auth/microsoft-callback'
    | '/org/enroll'
    | '/org/supporters'
    | '/policies/privacy-policy'
    | '/policies/terms-of-service'
    | '/admin/'
    | '/org/'
    | '/plans/'
    | '/plans/$planId/$entryId'
    | '/plans/$planId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AccountRoute: typeof AccountRoute
  CheckInRoute: typeof CheckInRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  PlayPulseRoute: typeof PlayPulseRoute
  ProgressRoute: typeof ProgressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SubscriptionRoute: typeof SubscriptionRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminChildrenRoute: typeof AdminChildrenRoute
  AdminEducatorsRoute: typeof AdminEducatorsRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminOrgsRoute: typeof AdminOrgsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminProgressRoute: typeof AdminProgressRoute
  AdminTtpRoute: typeof AdminTtpRoute
  AuthMicrosoftCallbackRoute: typeof AuthMicrosoftCallbackRoute
  OrgEnrollRoute: typeof OrgEnrollRoute
  OrgSupportersRoute: typeof OrgSupportersRoute
  PoliciesPrivacyPolicyRoute: typeof PoliciesPrivacyPolicyRoute
  PoliciesTermsOfServiceRoute: typeof PoliciesTermsOfServiceRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrgIndexRoute: typeof OrgIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  PlansPlanIdEntryIdRoute: typeof PlansPlanIdEntryIdRoute
  PlansPlanIdIndexRoute: typeof PlansPlanIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-pulse': {
      id: '/play-pulse'
      path: '/play-pulse'
      fullPath: '/play-pulse'
      preLoaderRoute: typeof PlayPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/children': {
      id: '/admin/children'
      path: '/admin/children'
      fullPath: '/admin/children'
      preLoaderRoute: typeof AdminChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/educators': {
      id: '/admin/educators'
      path: '/admin/educators'
      fullPath: '/admin/educators'
      preLoaderRoute: typeof AdminEducatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orgs': {
      id: '/admin/orgs'
      path: '/admin/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AdminOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/progress': {
      id: '/admin/progress'
      path: '/admin/progress'
      fullPath: '/admin/progress'
      preLoaderRoute: typeof AdminProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ttp': {
      id: '/admin/ttp'
      path: '/admin/ttp'
      fullPath: '/admin/ttp'
      preLoaderRoute: typeof AdminTtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/microsoft-callback': {
      id: '/auth/microsoft-callback'
      path: '/auth/microsoft-callback'
      fullPath: '/auth/microsoft-callback'
      preLoaderRoute: typeof AuthMicrosoftCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/org'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/enroll': {
      id: '/org/enroll'
      path: '/org/enroll'
      fullPath: '/org/enroll'
      preLoaderRoute: typeof OrgEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/supporters': {
      id: '/org/supporters'
      path: '/org/supporters'
      fullPath: '/org/supporters'
      preLoaderRoute: typeof OrgSupportersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy-policy': {
      id: '/policies/privacy-policy'
      path: '/policies/privacy-policy'
      fullPath: '/policies/privacy-policy'
      preLoaderRoute: typeof PoliciesPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/terms-of-service': {
      id: '/policies/terms-of-service'
      path: '/policies/terms-of-service'
      fullPath: '/policies/terms-of-service'
      preLoaderRoute: typeof PoliciesTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId/': {
      id: '/plans/$planId/'
      path: '/plans/$planId'
      fullPath: '/plans/$planId/'
      preLoaderRoute: typeof PlansPlanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId/$entryId': {
      id: '/plans/$planId/$entryId'
      path: '/plans/$planId/$entryId'
      fullPath: '/plans/$planId/$entryId'
      preLoaderRoute: typeof PlansPlanIdEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AccountRoute: AccountRoute,
  CheckInRoute: CheckInRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  PlayPulseRoute: PlayPulseRoute,
  ProgressRoute: ProgressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SubscriptionRoute: SubscriptionRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminChildrenRoute: AdminChildrenRoute,
  AdminEducatorsRoute: AdminEducatorsRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminOrgsRoute: AdminOrgsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminProgressRoute: AdminProgressRoute,
  AdminTtpRoute: AdminTtpRoute,
  AuthMicrosoftCallbackRoute: AuthMicrosoftCallbackRoute,
  OrgEnrollRoute: OrgEnrollRoute,
  OrgSupportersRoute: OrgSupportersRoute,
  PoliciesPrivacyPolicyRoute: PoliciesPrivacyPolicyRoute,
  PoliciesTermsOfServiceRoute: PoliciesTermsOfServiceRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrgIndexRoute: OrgIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  PlansPlanIdEntryIdRoute: PlansPlanIdEntryIdRoute,
  PlansPlanIdIndexRoute: PlansPlanIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
